# Diese Felder bitte nicht ändern.
Rang: 858
Wort: composer
Wortart: vt, vi, vr

# Diese Felder gerne verbessern!
Wort mit Artikel: composer
Femininum / Plural: ''
IPA: \kɔ̃.po.ze\
Definition: zusammenstellen, komponieren
Register: '' # Beispiel: ↘Sachtext ↗Mündlich

# Beispielsätze müssen durch Zeilenumbrüche getrennt werden.
# Zwischen jedem Paar kommen zwei Zeilenumbrüche.
Beispielsätze: |-
  Il avait juste besoin de *composer* mon numéro.
  Er musste nur meine Nummer *wählen*.

  Elle *compose* de la musique depuis son enfance.
  Sie *komponiert* seit ihrer Kindheit Musik.

  Le jury se *compose* de cinq experts.
  Die Jury *besteht* aus fünf Experten.

  J'ai *composé* un bouquet avec des fleurs du jardin.
  Ich habe aus Gartenblumen einen Strauß *zusammengestellt*.

  Cette symphonie a été *composée* au XIX<sup>e</sup> siècle.
  Diese Symphonie wurde im 19. Jahrhundert *komponiert*.

  Il a dû *composer* avec les exigences de sa famille.
  Er musste sich mit den Ansprüchen seiner Familie *arrangieren*.

  Les élèves *composent* en histoire aujourd'hui.
  Die Schüler *schreiben* heute eine Geschichtsarbeit.

  La matière vivante est *composée* de cellules.
  Die lebende Materie *besteht* aus Zellen.

  Elle *compose* son visage avant d'entrer dans la salle.
  Sie *nimmt* vor dem Betreten des Saals eine neutrale Miene *an*.

  Le poète a *composé* ce sonnet en une nuit.
  Der Dichter hat dieses Sonett in einer Nacht *verfasst*.

  L'équipe est *composée* de joueurs expérimentés.
  Das Team *besteht* aus erfahrenen Spielern.

  Il faut *composer* avec la réalité.
  Man muss sich mit der Realität *arrangieren*.

  Le chef *compose* un nouveau menu pour le restaurant.
  Der Koch *kreiert* ein neues Menü für das Restaurant.

  Cette substance se *compose* de plusieurs éléments.
  Diese Substanz *setzt* sich aus mehreren Elementen *zusammen*.

  L'architecte *compose* les plans du bâtiment.
  Der Architekt *erstellt* die Baupläne.

  Elle *compose* son personnage avec soin.
  Sie *gestaltet* ihre Rolle sorgfältig.

  L'orchestre joue une pièce *composée* par Mozart.
  Das Orchester spielt ein von Mozart *komponiertes* Stück.

  Il a dû *composer* avec ses principes.
  Er musste mit seinen Prinzipien einen Kompromiss *finden*.

  Le paysage se *compose* de collines et de vallées.
  Die Landschaft *besteht* aus Hügeln und Tälern.

  L'artiste *compose* une nouvelle toile.
  Der Künstler *gestaltet* ein neues Gemälde.

  Je dois *composer* avec mes moyens limités.
  Ich muss mit meinen begrenzten Mitteln *zurechtkommen*.

  L'auteur *compose* son roman chapitre par chapitre.
  Der Autor *verfasst* seinen Roman Kapitel für Kapitel.

  Cette équipe *compose* un groupe solide.
  Dieses Team *bildet* eine starke Einheit.

  Le musicien *compose* dans son studio.
  Der Musiker *komponiert* in seinem Studio.

  Elle *compose* soigneusement sa tenue.
  Sie *stellt* ihr Outfit sorgfältig *zusammen*.

  L'université se *compose* de plusieurs facultés.
  Die Universität *besteht* aus mehreren Fakultäten.

  Il *compose* un discours pour la cérémonie.
  Er *verfasst* eine Rede für die Zeremonie.

  Les danseurs *composent* une belle chorégraphie.
  Die Tänzer *gestalten* eine schöne Choreographie.

  Le comité se *compose* de membres élus.
  Das Komitee *setzt* sich aus gewählten Mitgliedern *zusammen*.

  Elle *compose* un poème d'amour.
  Sie *schreibt* ein Liebesgedicht.

  Cette région se *compose* de trois provinces.
  Diese Region *besteht* aus drei Provinzen.

  L'artiste *compose* une mosaïque colorée.
  Der Künstler *gestaltet* ein buntes Mosaik.

  Le parfumeur *compose* une nouvelle fragrance.
  Der Parfümeur *kreiert* einen neuen Duft.

  Ce groupe *compose* sa propre musique.
  Diese Band *komponiert* ihre eigene Musik.

  Il a dû *composer* avec les circonstances.
  Er musste sich den Umständen *anpassen*.

  Le photographe *compose* soigneusement son image.
  Der Fotograf *gestaltet* sein Bild sorgfältig.

  Cette collection se *compose* de pièces rares.
  Diese Sammlung *besteht* aus seltenen Stücken.

  L'écrivain *compose* ses mémoires.
  Der Schriftsteller *verfasst* seine Memoiren.

  Elle *compose* un cocktail original.
  Sie *kreiert* einen originellen Cocktail.

  Le puzzle se *compose* de mille pièces.
  Das Puzzle *besteht* aus tausend Teilen.

  Ce document *compose* un ensemble cohérent.
  Dieses Dokument *bildet* ein zusammenhängendes Ganzes.

  La chorale *compose* son programme.
  Der Chor *stellt* sein Programm *zusammen*.

  Cette somme se *compose* de plusieurs versements.
  Diese Summe *setzt* sich aus mehreren Zahlungen *zusammen*.

  Le peintre *compose* une nature morte.
  Der Maler *gestaltet* ein Stillleben.

  Cette formule se *compose* de trois éléments.
  Diese Formel *besteht* aus drei Elementen.

  L'architecte *compose* l'espace avec harmonie.
  Der Architekt *gestaltet* den Raum harmonisch.

  Le chef d'orchestre *compose* pour ses musiciens.
  Der Dirigent *komponiert* für seine Musiker.

# Notizen können HTML enthalten. Um Beispielsätze zu formatieren, gerne dieses Format benutzen:
# <div class="examples">
#   <div class="fr">Un homme et une femme.</div>
#   <div class="de spoiler">Ein Mann und eine Frau.</div>
# </div>
Notiz: ''
