# Diese Felder bitte nicht ändern.
Rang: 4716
Wort: configuration
Wortart: nf

# Diese Felder gerne verbessern!
Wort mit Artikel: la configuration
Femininum / Plural: ''
IPA: \kɔ̃.fi.ɡy.ʁa.sjɔ̃\
Definition: Beschaffenheit, Konfiguration
Register: ↗Sachtext

# Beispielsätze müssen durch Zeilenumbrüche getrennt werden.
# Zwischen jedem Paar kommen zwei Zeilenumbrüche.
Beispielsätze: |-
  La *configuration* institutionnelle rendrait une partition très difficile.
  Die institutionelle *Beschaffenheit* würde eine Teilung sehr schwierig machen.

  La *configuration* du terrain ne permet pas de construire ici.
  Die *Beschaffenheit* des Geländes erlaubt es nicht, hier zu bauen.

  La *configuration* de cette molécule est très complexe.
  Die *Form* dieses Moleküls ist sehr komplex.

  Pour changer la *configuration* de votre navigateur, allez dans les paramètres.
  Um die *Konfiguration* Ihres Browsers zu ändern, gehen Sie in die Einstellungen.

  Il faut respecter la *configuration* minimale requise pour installer ce jeu.
  Man muss die minimalen *System*voraussetzungen erfüllen, um dieses Spiel zu installieren.

  La *configuration* de cette vallée offre une protection naturelle contre le vent.
  Die *Beschaffenheit* dieses Tals bietet einen natürlichen Schutz gegen den Wind.

  J'ai besoin d'aide pour la *configuration* automatique de mon réseau WiFi.
  Ich brauche Hilfe bei der automatischen *Konfiguration* meines WLAN-Netzwerks.

  La *configuration* matérielle de mon ordinateur n'est plus à jour.
  Die Hardware-*Konfiguration* meines Computers ist nicht mehr aktuell.

  Les cristaux de sel présentent une *configuration* géométrique particulière.
  Salzkristalle weisen eine besondere geometrische *Form* auf.

  La *configuration* électronique de cet atome est stable.
  Die elektronische *Konfiguration* dieses Atoms ist stabil.

  Vérifiez la *configuration* requise avant d'acheter ce logiciel.
  Überprüfen Sie die *System*voraussetzungen, bevor Sie diese Software kaufen.

  La *configuration* de cette île en fait un paradis pour les oiseaux marins.
  Die *Beschaffenheit* dieser Insel macht sie zu einem Paradies für Seevögel.

  Le fichier de *configuration* a été corrompu lors de la mise à jour.
  Die *Konfigurations*datei wurde während des Updates beschädigt.

  La *configuration* de mon PC ne me permet pas de faire tourner ce programme.
  Die *Konfiguration* meines PCs erlaubt es mir nicht, dieses Programm laufen zu lassen.

  L'astrologue étudie la *configuration* des planètes au moment de la naissance.
  Der Astrologe untersucht die *Konstellation* der Planeten zum Zeitpunkt der Geburt.

  Une *configuration* manuelle du routeur sera nécessaire.
  Eine manuelle *Konfiguration* des Routers wird erforderlich sein.

  La *configuration* du sol rend l'agriculture difficile dans cette région.
  Die *Beschaffenheit* des Bodens macht die Landwirtschaft in dieser Region schwierig.

  Selon la *configuration* actuelle des astres, le moment est propice.
  Der aktuellen *Konstellation* der Gestirne nach ist der Moment günstig.

  La *configuration* de ces points dans l'espace forme un triangle.
  Die *Anordnung* dieser Punkte im Raum bildet ein Dreieck.

  Cette *configuration* géographique est typique des fjords norvégiens.
  Diese geografische *Beschaffenheit* ist typisch für norwegische Fjorde.

  La nouvelle *configuration* du système offre de meilleures performances.
  Die neue System*konfiguration* bietet bessere Leistung.

# Notizen können HTML enthalten. Um Beispielsätze zu formatieren, gerne dieses Format benutzen:
# <div class="examples">
#   <div class="fr">Un homme et une femme.</div>
#   <div class="de spoiler">Ein Mann und eine Frau.</div>
# </div>
Notiz: ''
